name: Upload to S3

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ AKIAV7EIGDYC4PKEBAFD }}
          aws-secret-access-key: ${{ biXa0ZeUQZrDabRQ8d8KvX9xSINlVClLC+hPSZF0 }}
          aws-region: ${{ us-west-1 }}

      - name: Upload file to S3
        run: |
          aws s3 cp path/to/your/file s3://$S3_BUCKET_NAME/ --recursive
        env:
          S3_BUCKET_NAME: ${{ s3_jeevesh }}

