name: Upload index.html to S3

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload index.html to S3
        run: aws s3 cp index.html s3://$S3_BUCKET_NAME/index.html
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}









